apiVersion: config.418.cloud/v2
kind: ProjectConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: b1ba06c1.418.cloud
domain: ${config_domain}
protocol: https
resourceGroupName: teapot-shadow-rg
tlsSecret: ${config_tls_secret}