# permissions for end users to view teapotapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teapotapp-viewer-role
rules:
- apiGroups:
  - k8s.418.cloud
  resources:
  - teapotapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.418.cloud
  resources:
  - teapotapps/status
  verbs:
  - get
