apiVersion: azure.418.cloud/v1alpha1
kind: ContainerApp
metadata:
  name: containerapp-sample
spec:
  containerEnvironmentName: containerenvironment-sample
  targetPort: 8080
  containersTemplate:
    name: traefik-whoami
    image: ghcr.io/418-cloud/testapp:v0.0.1
    args:
    - -response=Hello from azure 
    resources:
      cpu: ".25"
      memory: ".5Gi"