name: Build release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get version from tags
      id: version
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: |
        make test
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:v${{ steps.version.outputs.tag }}